// SPDX-License-Identifier: GPL-3.0-or-later

// Package parser contains the language parser.
//
// It turns a sequence of tokens (defined into the token package
// and generated by the scanner package) into a sequence of abstract
// syntax tree (AST) nodes (defined into the ast package).
package parser
